<?php

declare(strict_types=1);

/**
 * SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

namespace Unit\Search;

use OC\Collaboration\Reference\LinkReferenceProvider;
use OC\Collaboration\Reference\ReferenceManager;
use OCA\Collectives\Reference\SearchablePageReferenceProvider;
use OCA\Collectives\Service\CollectiveService;
use OCA\Collectives\Service\PageService;
use OCA\Collectives\Service\SharePageService;
use OCP\Collaboration\Reference\IPublicReferenceProvider;
use OCP\IDateTimeFormatter;
use OCP\IL10N;
use OCP\IURLGenerator;
use PHPUnit\Framework\TestCase;

class SearchablePageReferenceProviderTest extends TestCase {
	private SearchablePageReferenceProvider $provider;
	protected function setUp(): void {
		$this->needsIPublicReferenceProvider();
		parent::setUp(); // TODO: Change the autogenerated stub
		$collectiveService = $this->createMock(CollectiveService::class);
		$pageService = $this->createMock(PageService::class);
		$sharePageService = $this->createMock(SharePageService::class);
		$l10n = $this->createMock(IL10N::class);
		$urlGenerator = $this->createMock(IURLGenerator::class);
		$urlGenerator->method('getAbsoluteURL')->willReturnMap([
			['/apps/collectives/p', 'https://nextcloud.local/apps/collectives/p'],
			['/index.php/apps/collectives/p', 'https://nextcloud.local/index.php/apps/collectives/p'],
			['/apps/collectives', 'https://nextcloud.local/apps/collectives'],
			['/index.php/apps/collectives', 'https://nextcloud.local/index.php/apps/collectives'],
		]);
		$dateTimeFormatter = $this->createMock(IDateTimeFormatter::class);
		$referenceManager = $this->createMock(ReferenceManager::class);
		$linkReferenceProvider = $this->createMock(LinkReferenceProvider::class);
		$uid = 'jane';
		$this->provider = new SearchablePageReferenceProvider(
			$collectiveService,
			$pageService,
			$sharePageService,
			$l10n,
			$urlGenerator,
			$dateTimeFormatter,
			$referenceManager,
			$linkReferenceProvider,
			$uid,
		);
	}

	private function needsIPublicReferenceProvider(): void {
		if (!interface_exists(IPublicReferenceProvider::class)) {
			$this->markTestSkipped('IPublicReferenceProvider not available.');
		}
	}

	private function slugUrlProvider(): array {
		return [
			// internal
			['https://nextcloud.local/apps/collectives/supacollective-123/spectre-slug-14457', 'spectre-slug-14457', null],
			['https://nextcloud.local/apps/collectives/supacollective-123/spectre-slug-14457#h-heading1', 'spectre-slug-14457', 'h-heading1'],

			// public
			['https://nextcloud.local/apps/collectives/p/MsdwSCmP9F6jcQX/supacollective-123/spectre-slug-14457', 'spectre-slug-14457', null],
			['https://nextcloud.local/apps/collectives/p/MsdwSCmP9F6jcQX/supacollective-123/spectre-slug-14457#h-heading1', 'spectre-slug-14457', 'h-heading1'],
		];
	}

	private function urlProvider(): array {
		return [
			// internal
			['https://nextcloud.local/apps/collectives/supacollective', '', null],
			['https://nextcloud.local/apps/collectives/supacollective/Tutos/Hacking/Spectre', 'Tutos/Hacking/Spectre', null],
			['https://nextcloud.local/apps/collectives/supacollective/Tutos/Hacking/Spectre#h-heading1', 'Tutos/Hacking/Spectre', 'h-heading1'],
			['https://nextcloud.local/index.php/apps/collectives/supacollective/Tutos/Hacking/Spectre', 'Tutos/Hacking/Spectre', null],

			// public
			['https://nextcloud.local/apps/collectives/p/MsdwSCmP9F6jcQX/supacollective', '', null],
			['https://nextcloud.local/apps/collectives/p/MsdwSCmP9F6jcQX/supacollective/abc', 'abc', null],
			['https://nextcloud.local/apps/collectives/p/MsdwSCmP9F6jcQX/supacollective/Tutos/Hacking/Spectre', 'Tutos/Hacking/Spectre', null],
			['https://nextcloud.local/apps/collectives/p/MsdwSCmP9F6jcQX/supacollective/Tutos/Hacking/Spectre#h-heading1', 'Tutos/Hacking/Spectre', 'h-heading1'],
			['https://nextcloud.local/index.php/apps/collectives/p/MsdwSCmP9F6jcQX/supacollective/Tutos/Hacking/Spectre', 'Tutos/Hacking/Spectre', null],
		];
	}

	private function urlFileIdProvider(): array {
		return [
			// internal
			['https://nextcloud.local/apps/collectives/supacollective/Tutos/Hacking/Spectre?fileId=14457', 'Tutos/Hacking/Spectre', null],
			['https://nextcloud.local/apps/collectives/supacollective/Tutos/Hacking/Spectre?fileId=14457#h-heading1', 'Tutos/Hacking/Spectre', 'h-heading1'],
			['https://nextcloud.local/index.php/apps/collectives/supacollective/Tutos/Hacking/Spectre?fileId=14457', 'Tutos/Hacking/Spectre', null],

			// public
			['https://nextcloud.local/apps/collectives/p/MsdwSCmP9F6jcQX/supacollective/Tutos/Hacking/Spectre?fileId=14457', 'Tutos/Hacking/Spectre', null],
			['https://nextcloud.local/apps/collectives/p/MsdwSCmP9F6jcQX/supacollective/Tutos/Hacking/Spectre?fileId=14457#h-heading1', 'Tutos/Hacking/Spectre', 'h-heading1'],
			['https://nextcloud.local/index.php/apps/collectives/p/MsdwSCmP9F6jcQX/supacollective/Tutos/Hacking/Spectre?fileId=14457', 'Tutos/Hacking/Spectre', null],
		];
	}

	private function nonMatchingUrlProvider(): array {
		return [
			['https://nextcloud.local/apps/contacts/All%20contacts/abc'],
			['https://nextcloud.local/index.php/apps/contacts/All%20contacts/abc'],
			['https://nextcloud.local/apps/collectives/'],
		];
	}

	/**
	 * @dataProvider slugUrlProvider
	 */
	public function testMatchSlugUrl(string $url, string $pagePath, ?string $fragment): void {
		$expectedPagePath = [
			'collectiveName' => 'supacollective',
			'pagePath' => $pagePath,
			'fileId' => 14457,
			'collectiveId' => 123,
			'fragment' => $fragment,
		];

		self::assertEquals($expectedPagePath, $this->provider->matchUrl($url));
	}

	/**
	 * @dataProvider urlProvider
	 */
	public function testMatchUrl(string $url, string $pagePath, ?string $fragment): void {
		$expectedPagePath = [
			'collectiveName' => 'supacollective',
			'pagePath' => $pagePath,
			'fragment' => $fragment,
		];

		self::assertEquals($expectedPagePath, $this->provider->matchUrl($url));
	}

	/**
	 * @dataProvider urlFileIdProvider
	 */
	public function testMatchUrlFileId(string $url, string $pagePath, ?string $fragment): void {
		$expectedPagePath = [
			'collectiveName' => 'supacollective',
			'pagePath' => $pagePath,
			'fileId' => 14457,
			'fragment' => $fragment,
		];

		self::assertEquals($expectedPagePath, $this->provider->matchUrl($url));
	}

	/**
	 * @dataProvider nonMatchingUrlProvider
	 */
	public function testMatchUrlNonMatching(string $url): void {
		self::assertEquals(null, $this->provider->matchUrl($url));
	}
}
