# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

# SPDX-FileCopyrightText: 2020 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

name = "custom"
license = "MIT"
licenselink = "https://github.com/vjeantet/hugo-theme-docdock/blob/master/LICENSE.md"
description = "Customization of the docdock theme for collectives"
tags = ["documentation", "custom"]
min_version = 0.42

[author]
  name = "Azul"
