// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseURL: `${string}://openapi.json` | (string & {})
}

export type Collective = {
	id: number
	circleId: string
	emoji?: string
	trashTimestamp?: number
	pageMode: number
	name: string
	level: number
	editPermissionLevel: number
	sharePermissionLevel: number
	canEdit: boolean
	canShare: boolean
	shareToken?: string
	isPageShare: boolean
	sharePageId?: number
	shareEditable: boolean
	userPageOrder: number
	userShowMembers: boolean
	userShowRecentPages: boolean
	userFavoritePages: Array<number>
	canLeave: boolean
}

export type CollectiveShare = {
	id: number
	collectiveId: number
	pageId: number
	token: string
	owner: string
	editable: boolean
	password: string
}

export type OcsMeta = {
	status: string
	statuscode: number
	message?: string
	totalitems?: string
	itemsperpage?: string
}

export type PageAttachment = {
	id: number
	name: string
	filesize: number
	mimetype: string
	timestamp: number
	path: string
	internalPath: string
	hasPreview: boolean
}

export type PageInfo = {
	id: number
	lastUserId?: string
	lastUserDisplayName?: string
	emoji?: string
	isFullWidth: boolean
	subpageOrder: Array<number>
	trashTimestamp?: number
	title: string
	timestamp: number
	size: number
	fileName: string
	filePath: string
	collectivePath: string
	parentId: number
	shareToken?: string
}

export type Tag = {
	id: number
	collectiveId: number
	name: string
	color: string
}

export type CollectiveIndexData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives'
}

export type CollectiveIndexErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Something not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type CollectiveIndexError = CollectiveIndexErrors[keyof CollectiveIndexErrors]

export type CollectiveIndexResponses = {
	/**
	 * Collectives returned
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				collectives: Array<Collective>
			}
		}
	}
}

export type CollectiveIndexResponse = CollectiveIndexResponses[keyof CollectiveIndexResponses]

export type CollectiveCreateData = {
	body: {
		/**
		 * Name of the collective
		 */
		name: string
		/**
		 * Optional emoji
		 */
		emoji?: string | null
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives'
}

export type CollectiveCreateErrors = {
	/**
	 * Collective or team already exists
	 */
	400: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Something not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type CollectiveCreateError = CollectiveCreateErrors[keyof CollectiveCreateErrors]

export type CollectiveCreateResponses = {
	/**
	 * Collective created
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				collective: Collective
				info: string
			}
		}
	}
}

export type CollectiveCreateResponse = CollectiveCreateResponses[keyof CollectiveCreateResponses]

export type CollectiveTrashData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{id}'
}

export type CollectiveTrashErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type CollectiveTrashError = CollectiveTrashErrors[keyof CollectiveTrashErrors]

export type CollectiveTrashResponses = {
	/**
	 * Collective trashed
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				collective: Collective
			}
		}
	}
}

export type CollectiveTrashResponse = CollectiveTrashResponses[keyof CollectiveTrashResponses]

export type CollectiveUpdateData = {
	body?: {
		/**
		 * Optional emoji
		 */
		emoji?: string | null
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{id}'
}

export type CollectiveUpdateErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type CollectiveUpdateError = CollectiveUpdateErrors[keyof CollectiveUpdateErrors]

export type CollectiveUpdateResponses = {
	/**
	 * Collective updated
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				collective: Collective
			}
		}
	}
}

export type CollectiveUpdateResponse = CollectiveUpdateResponses[keyof CollectiveUpdateResponses]

export type CollectiveEditLevelData = {
	body: {
		/**
		 * Edit level
		 */
		level: number
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{id}/editLevel'
}

export type CollectiveEditLevelErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type CollectiveEditLevelError = CollectiveEditLevelErrors[keyof CollectiveEditLevelErrors]

export type CollectiveEditLevelResponses = {
	/**
	 * Collective updated
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				collective: Collective
			}
		}
	}
}

export type CollectiveEditLevelResponse = CollectiveEditLevelResponses[keyof CollectiveEditLevelResponses]

export type CollectiveShareLevelData = {
	body: {
		/**
		 * Share level
		 */
		level: number
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{id}/shareLevel'
}

export type CollectiveShareLevelErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type CollectiveShareLevelError = CollectiveShareLevelErrors[keyof CollectiveShareLevelErrors]

export type CollectiveShareLevelResponses = {
	/**
	 * Collective updated
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				collective: Collective
			}
		}
	}
}

export type CollectiveShareLevelResponse = CollectiveShareLevelResponses[keyof CollectiveShareLevelResponses]

export type CollectivePageModeData = {
	body: {
		/**
		 * Page edit mode
		 */
		mode: number
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{id}/pageMode'
}

export type CollectivePageModeErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type CollectivePageModeError = CollectivePageModeErrors[keyof CollectivePageModeErrors]

export type CollectivePageModeResponses = {
	/**
	 * Collective updated
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				collective: Collective
			}
		}
	}
}

export type CollectivePageModeResponse = CollectivePageModeResponses[keyof CollectivePageModeResponses]

export type TrashIndexData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/trash'
}

export type TrashIndexErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Something not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type TrashIndexError = TrashIndexErrors[keyof TrashIndexErrors]

export type TrashIndexResponses = {
	/**
	 * Trashed collectives returned
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				collectives: Array<Collective>
			}
		}
	}
}

export type TrashIndexResponse = TrashIndexResponses[keyof TrashIndexResponses]

export type TrashDeleteData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		id: number
	}
	query?: {
		/**
		 * Whether to delete the team/circle as well (optional, default: false)
		 */
		circle?: boolean
	}
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/trash/{id}'
}

export type TrashDeleteErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type TrashDeleteError = TrashDeleteErrors[keyof TrashDeleteErrors]

export type TrashDeleteResponses = {
	/**
	 * Trashed collective deleted
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				collective: Collective
			}
		}
	}
}

export type TrashDeleteResponse = TrashDeleteResponses[keyof TrashDeleteResponses]

export type TrashRestoreData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/trash/{id}'
}

export type TrashRestoreErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type TrashRestoreError = TrashRestoreErrors[keyof TrashRestoreErrors]

export type TrashRestoreResponses = {
	/**
	 * Trashed collective restored
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				collective: Collective
			}
		}
	}
}

export type TrashRestoreResponse = TrashRestoreResponses[keyof TrashRestoreResponses]

export type ShareGetCollectiveSharesData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/shares'
}

export type ShareGetCollectiveSharesErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type ShareGetCollectiveSharesError = ShareGetCollectiveSharesErrors[keyof ShareGetCollectiveSharesErrors]

export type ShareGetCollectiveSharesResponses = {
	/**
	 * Shares returned
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: Array<CollectiveShare>
		}
	}
}

export type ShareGetCollectiveSharesResponse = ShareGetCollectiveSharesResponses[keyof ShareGetCollectiveSharesResponses]

export type ShareCreateCollectiveShareData = {
	body?: {
		/**
		 * Optional password for the share
		 */
		password?: string
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/shares'
}

export type ShareCreateCollectiveShareErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type ShareCreateCollectiveShareError = ShareCreateCollectiveShareErrors[keyof ShareCreateCollectiveShareErrors]

export type ShareCreateCollectiveShareResponses = {
	/**
	 * Share created
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: CollectiveShare
		}
	}
}

export type ShareCreateCollectiveShareResponse = ShareCreateCollectiveShareResponses[keyof ShareCreateCollectiveShareResponses]

export type ShareCreatePageShareData = {
	body?: {
		/**
		 * Optional password for the share
		 */
		password?: string
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the page
		 */
		pageId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/{pageId}/shares'
}

export type ShareCreatePageShareErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type ShareCreatePageShareError = ShareCreatePageShareErrors[keyof ShareCreatePageShareErrors]

export type ShareCreatePageShareResponses = {
	/**
	 * Share created
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: CollectiveShare
		}
	}
}

export type ShareCreatePageShareResponse = ShareCreatePageShareResponses[keyof ShareCreatePageShareResponses]

export type ShareDeletePageShareData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the page
		 */
		pageId: number
		/**
		 * Token of the share
		 */
		token: string
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/{pageId}/shares/{token}'
}

export type ShareDeletePageShareErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective, page or share not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type ShareDeletePageShareError = ShareDeletePageShareErrors[keyof ShareDeletePageShareErrors]

export type ShareDeletePageShareResponses = {
	/**
	 * Share deleted
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type ShareDeletePageShareResponse = ShareDeletePageShareResponses[keyof ShareDeletePageShareResponses]

export type ShareUpdatePageShareData = {
	body: {
		/**
		 * Whether share has edit permissions
		 */
		editable: boolean
		/**
		 * Optional password for the share
		 */
		password?: string | null
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the page
		 */
		pageId: number
		/**
		 * Token of the share
		 */
		token: string
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/{pageId}/shares/{token}'
}

export type ShareUpdatePageShareErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective, page or share not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type ShareUpdatePageShareError = ShareUpdatePageShareErrors[keyof ShareUpdatePageShareErrors]

export type ShareUpdatePageShareResponses = {
	/**
	 * Share updated
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: CollectiveShare
		}
	}
}

export type ShareUpdatePageShareResponse = ShareUpdatePageShareResponses[keyof ShareUpdatePageShareResponses]

export type ShareDeleteCollectiveShareData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * Token of the share
		 */
		token: string
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/shares/{token}'
}

export type ShareDeleteCollectiveShareErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or share not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type ShareDeleteCollectiveShareError = ShareDeleteCollectiveShareErrors[keyof ShareDeleteCollectiveShareErrors]

export type ShareDeleteCollectiveShareResponses = {
	/**
	 * Share deleted
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type ShareDeleteCollectiveShareResponse = ShareDeleteCollectiveShareResponses[keyof ShareDeleteCollectiveShareResponses]

export type ShareUpdateCollectiveShareData = {
	body: {
		/**
		 * Whether share has edit permissions
		 */
		editable: boolean
		/**
		 * Optional password for the share
		 */
		password?: string
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * Token of the share
		 */
		token: string
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/shares/{token}'
}

export type ShareUpdateCollectiveShareErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective, page or share not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type ShareUpdateCollectiveShareError = ShareUpdateCollectiveShareErrors[keyof ShareUpdateCollectiveShareErrors]

export type ShareUpdateCollectiveShareResponses = {
	/**
	 * Share updated
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: CollectiveShare
		}
	}
}

export type ShareUpdateCollectiveShareResponse = ShareUpdateCollectiveShareResponses[keyof ShareUpdateCollectiveShareResponses]

export type PageContentSearchData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
	}
	query: {
		/**
		 * String to search for
		 */
		searchString: string
	}
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/search'
}

export type PageContentSearchErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageContentSearchError = PageContentSearchErrors[keyof PageContentSearchErrors]

export type PageContentSearchResponses = {
	/**
	 * Found pages returned
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				pages: Array<PageInfo>
			}
		}
	}
}

export type PageContentSearchResponse = PageContentSearchResponses[keyof PageContentSearchResponses]

export type PageIndexData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages'
}

export type PageIndexErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageIndexError = PageIndexErrors[keyof PageIndexErrors]

export type PageIndexResponses = {
	/**
	 * Pages returned
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				pages: Array<PageInfo>
			}
		}
	}
}

export type PageIndexResponse = PageIndexResponses[keyof PageIndexResponses]

export type PageTrashData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/{id}'
}

export type PageTrashErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageTrashError = PageTrashErrors[keyof PageTrashErrors]

export type PageTrashResponses = {
	/**
	 * Page trashed
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				page: PageInfo
			}
		}
	}
}

export type PageTrashResponse = PageTrashResponses[keyof PageTrashResponses]

export type PageGetData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/{id}'
}

export type PageGetErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageGetError = PageGetErrors[keyof PageGetErrors]

export type PageGetResponses = {
	/**
	 * Page returned
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				page: PageInfo
			}
		}
	}
}

export type PageGetResponse = PageGetResponses[keyof PageGetResponses]

export type PageMoveOrCopyData = {
	body?: {
		/**
		 * ID of target parent page (optional)
		 */
		parentId?: number | null
		/**
		 * Target title (optional)
		 */
		title?: string | null
		/**
		 * Index in subpage order (optional, default 0)
		 */
		index?: number | null
		/**
		 * Copy the page instead of move (optional, default false)
		 */
		copy?: boolean
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/{id}'
}

export type PageMoveOrCopyErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or (parent) page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageMoveOrCopyError = PageMoveOrCopyErrors[keyof PageMoveOrCopyErrors]

export type PageMoveOrCopyResponses = {
	/**
	 * Page moved/copied
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				page: PageInfo
			}
		}
	}
}

export type PageMoveOrCopyResponse = PageMoveOrCopyResponses[keyof PageMoveOrCopyResponses]

export type PageCreateData = {
	body: {
		/**
		 * Title of the page
		 */
		title: string
		/**
		 * ID of the template page to use
		 */
		templateId?: number | null
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the parent page
		 */
		parentId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/{parentId}'
}

export type PageCreateErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or parent/template page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageCreateError = PageCreateErrors[keyof PageCreateErrors]

export type PageCreateResponses = {
	/**
	 * New page created
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				page: PageInfo
			}
		}
	}
}

export type PageCreateResponse = PageCreateResponses[keyof PageCreateResponses]

export type PageTouchData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/{id}/touch'
}

export type PageTouchErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or parent/template page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageTouchError = PageTouchErrors[keyof PageTouchErrors]

export type PageTouchResponses = {
	/**
	 * Page touched
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				page: PageInfo
			}
		}
	}
}

export type PageTouchResponse = PageTouchResponses[keyof PageTouchResponses]

export type PageSetFullWidthData = {
	body: {
		/**
		 * Whether to enable full width view for the page
		 */
		fullWidth: boolean
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/{id}/fullWidth'
}

export type PageSetFullWidthErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageSetFullWidthError = PageSetFullWidthErrors[keyof PageSetFullWidthErrors]

export type PageSetFullWidthResponses = {
	/**
	 * Full width view set/unset
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				page: PageInfo
			}
		}
	}
}

export type PageSetFullWidthResponse = PageSetFullWidthResponses[keyof PageSetFullWidthResponses]

export type PageMoveOrCopyToCollectiveData = {
	body?: {
		/**
		 * ID of target parent page (optional)
		 */
		parentId?: number | null
		/**
		 * Index in subpage order (optional, default 0)
		 */
		index?: number | null
		/**
		 * Copy the page instead of move (optional, default false)
		 */
		copy?: boolean
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the page
		 */
		id: number
		/**
		 * ID of the target collective
		 */
		newCollectiveId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/{id}/to/{newCollectiveId}'
}

export type PageMoveOrCopyToCollectiveErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or (parent) page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageMoveOrCopyToCollectiveError = PageMoveOrCopyToCollectiveErrors[keyof PageMoveOrCopyToCollectiveErrors]

export type PageMoveOrCopyToCollectiveResponses = {
	/**
	 * Page moved/copied
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageMoveOrCopyToCollectiveResponse = PageMoveOrCopyToCollectiveResponses[keyof PageMoveOrCopyToCollectiveResponses]

export type PageSetEmojiData = {
	body?: {
		/**
		 * Emoji to set or null to unset (optional, default null)
		 */
		emoji?: string | null
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/{id}/emoji'
}

export type PageSetEmojiErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageSetEmojiError = PageSetEmojiErrors[keyof PageSetEmojiErrors]

export type PageSetEmojiResponses = {
	/**
	 * Emoji set/unset
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				page: PageInfo
			}
		}
	}
}

export type PageSetEmojiResponse = PageSetEmojiResponses[keyof PageSetEmojiResponses]

export type PageSetSubpageOrderData = {
	body?: {
		/**
		 * JSON-stringified array of subpage IDs
		 */
		subpageOrder?: string | null
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/{id}/subpageOrder'
}

export type PageSetSubpageOrderErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageSetSubpageOrderError = PageSetSubpageOrderErrors[keyof PageSetSubpageOrderErrors]

export type PageSetSubpageOrderResponses = {
	/**
	 * Subpage order set
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				page: PageInfo
			}
		}
	}
}

export type PageSetSubpageOrderResponse = PageSetSubpageOrderResponses[keyof PageSetSubpageOrderResponses]

export type PageRemoveTagData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the page
		 */
		id: number
		/**
		 * ID of the tag to remove
		 */
		tagId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/{id}/tags/{tagId}'
}

export type PageRemoveTagErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageRemoveTagError = PageRemoveTagErrors[keyof PageRemoveTagErrors]

export type PageRemoveTagResponses = {
	/**
	 * Tag removed
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				page: PageInfo
			}
		}
	}
}

export type PageRemoveTagResponse = PageRemoveTagResponses[keyof PageRemoveTagResponses]

export type PageAddTagData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the page
		 */
		id: number
		/**
		 * ID of the tag to add
		 */
		tagId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/{id}/tags/{tagId}'
}

export type PageAddTagErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageAddTagError = PageAddTagErrors[keyof PageAddTagErrors]

export type PageAddTagResponses = {
	/**
	 * Tag added
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				page: PageInfo
			}
		}
	}
}

export type PageAddTagResponse = PageAddTagResponses[keyof PageAddTagResponses]

export type PageGetAttachmentsData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/{id}/attachments'
}

export type PageGetAttachmentsErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageGetAttachmentsError = PageGetAttachmentsErrors[keyof PageGetAttachmentsErrors]

export type PageGetAttachmentsResponses = {
	/**
	 * Attachments returned
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				attachments: Array<PageAttachment>
			}
		}
	}
}

export type PageGetAttachmentsResponse = PageGetAttachmentsResponses[keyof PageGetAttachmentsResponses]

export type PageUploadAttachmentData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/{id}/attachments'
}

export type PageUploadAttachmentErrors = {
	/**
	 * Invalid file upload
	 */
	400: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageUploadAttachmentError = PageUploadAttachmentErrors[keyof PageUploadAttachmentErrors]

export type PageUploadAttachmentResponses = {
	/**
	 * Attachment uploaded
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				attachment: PageAttachment
			}
		}
	}
}

export type PageUploadAttachmentResponse = PageUploadAttachmentResponses[keyof PageUploadAttachmentResponses]

export type PageDeleteAttachmentData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the page
		 */
		id: number
		/**
		 * ID of the attachment
		 */
		attachmentId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/{id}/attachments/{attachmentId}'
}

export type PageDeleteAttachmentErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective, page or attachment not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageDeleteAttachmentError = PageDeleteAttachmentErrors[keyof PageDeleteAttachmentErrors]

export type PageDeleteAttachmentResponses = {
	/**
	 * Attachment deleted
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageDeleteAttachmentResponse = PageDeleteAttachmentResponses[keyof PageDeleteAttachmentResponses]

export type PageRenameAttachmentData = {
	body: {
		/**
		 * Target name
		 */
		name: string
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the page
		 */
		id: number
		/**
		 * ID of the attachment
		 */
		attachmentId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/{id}/attachments/{attachmentId}'
}

export type PageRenameAttachmentErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective, page or attachment not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageRenameAttachmentError = PageRenameAttachmentErrors[keyof PageRenameAttachmentErrors]

export type PageRenameAttachmentResponses = {
	/**
	 * Attachment renamed
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				attachment: PageAttachment
			}
		}
	}
}

export type PageRenameAttachmentResponse = PageRenameAttachmentResponses[keyof PageRenameAttachmentResponses]

export type PageRestoreAttachmentData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the page
		 */
		id: number
		/**
		 * ID of the attachment
		 */
		attachmentId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/{id}/attachments/trash/{attachmentId}'
}

export type PageRestoreAttachmentErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective, page or attachment not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageRestoreAttachmentError = PageRestoreAttachmentErrors[keyof PageRestoreAttachmentErrors]

export type PageRestoreAttachmentResponses = {
	/**
	 * Attachment restored
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				attachment: PageAttachment
			}
		}
	}
}

export type PageRestoreAttachmentResponse = PageRestoreAttachmentResponses[keyof PageRestoreAttachmentResponses]

export type PageTrashIndexData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/trash'
}

export type PageTrashIndexErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageTrashIndexError = PageTrashIndexErrors[keyof PageTrashIndexErrors]

export type PageTrashIndexResponses = {
	/**
	 * Trashed pages returned
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				pages: Array<PageInfo>
			}
		}
	}
}

export type PageTrashIndexResponse = PageTrashIndexResponses[keyof PageTrashIndexResponses]

export type PageTrashDeleteData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the trashed page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/trash/{id}'
}

export type PageTrashDeleteErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageTrashDeleteError = PageTrashDeleteErrors[keyof PageTrashDeleteErrors]

export type PageTrashDeleteResponses = {
	/**
	 * Trashed page deleted
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageTrashDeleteResponse = PageTrashDeleteResponses[keyof PageTrashDeleteResponses]

export type PageTrashRestoreData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the trashed page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/trash/{id}'
}

export type PageTrashRestoreErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PageTrashRestoreError = PageTrashRestoreErrors[keyof PageTrashRestoreErrors]

export type PageTrashRestoreResponses = {
	/**
	 * Trashed page restored
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				page: PageInfo
			}
		}
	}
}

export type PageTrashRestoreResponse = PageTrashRestoreResponses[keyof PageTrashRestoreResponses]

export type TemplateIndexData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/templates'
}

export type TemplateIndexErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type TemplateIndexError = TemplateIndexErrors[keyof TemplateIndexErrors]

export type TemplateIndexResponses = {
	/**
	 * Template pages returned
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				templates: Array<PageInfo>
			}
		}
	}
}

export type TemplateIndexResponse = TemplateIndexResponses[keyof TemplateIndexResponses]

export type TemplateDeleteData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the template page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/templates/{id}'
}

export type TemplateDeleteErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type TemplateDeleteError = TemplateDeleteErrors[keyof TemplateDeleteErrors]

export type TemplateDeleteResponses = {
	/**
	 * Template page deleted
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type TemplateDeleteResponse = TemplateDeleteResponses[keyof TemplateDeleteResponses]

export type TemplateCreateData = {
	body: {
		/**
		 * Title of the page
		 */
		title: string
		/**
		 * ID of the parent template page
		 */
		parentId: number
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		id: string
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/templates/{id}'
}

export type TemplateCreateErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or parent template page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type TemplateCreateError = TemplateCreateErrors[keyof TemplateCreateErrors]

export type TemplateCreateResponses = {
	/**
	 * New template page created
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				template: PageInfo
			}
		}
	}
}

export type TemplateCreateResponse = TemplateCreateResponses[keyof TemplateCreateResponses]

export type TemplateRenameData = {
	body: {
		/**
		 * New title of the template page
		 */
		title: string
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the template page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/templates/{id}'
}

export type TemplateRenameErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type TemplateRenameError = TemplateRenameErrors[keyof TemplateRenameErrors]

export type TemplateRenameResponses = {
	/**
	 * Template page renamed
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				template: PageInfo
			}
		}
	}
}

export type TemplateRenameResponse = TemplateRenameResponses[keyof TemplateRenameResponses]

export type TemplateSetEmojiData = {
	body?: {
		/**
		 * Emoji to set or null to unset (optional, default null)
		 */
		emoji?: string | null
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the template page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/pages/templates/{id}/emoji'
}

export type TemplateSetEmojiErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type TemplateSetEmojiError = TemplateSetEmojiErrors[keyof TemplateSetEmojiErrors]

export type TemplateSetEmojiResponses = {
	/**
	 * Emoji set/unset
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				template: PageInfo
			}
		}
	}
}

export type TemplateSetEmojiResponse = TemplateSetEmojiResponses[keyof TemplateSetEmojiResponses]

export type TagIndexData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/tags'
}

export type TagIndexErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Something not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type TagIndexError = TagIndexErrors[keyof TagIndexErrors]

export type TagIndexResponses = {
	/**
	 * Tags returned
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				tags: Array<Tag>
			}
		}
	}
}

export type TagIndexResponse = TagIndexResponses[keyof TagIndexResponses]

export type TagCreateData = {
	body: {
		/**
		 * Name of the tag
		 */
		name: string
		/**
		 * Color of the tag
		 */
		color: string
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/tags'
}

export type TagCreateErrors = {
	/**
	 * Tag already exists for the collective
	 */
	400: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type TagCreateError = TagCreateErrors[keyof TagCreateErrors]

export type TagCreateResponses = {
	/**
	 * Tag created
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				tag: Tag
				info: string
			}
		}
	}
}

export type TagCreateResponse = TagCreateResponses[keyof TagCreateResponses]

export type TagDeleteData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the tag
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/tags/{id}'
}

export type TagDeleteErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or tag not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type TagDeleteError = TagDeleteErrors[keyof TagDeleteErrors]

export type TagDeleteResponses = {
	/**
	 * Tag deleted
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type TagDeleteResponse = TagDeleteResponses[keyof TagDeleteResponses]

export type TagUpdateData = {
	body: {
		/**
		 * Name of the tag
		 */
		name: string
		/**
		 * Color of the tag
		 */
		color: string
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
		/**
		 * ID of the tag
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/tags/{id}'
}

export type TagUpdateErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or tag not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type TagUpdateError = TagUpdateErrors[keyof TagUpdateErrors]

export type TagUpdateResponses = {
	/**
	 * Tag updated
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				tag: Tag
			}
		}
	}
}

export type TagUpdateResponse = TagUpdateResponses[keyof TagUpdateResponses]

export type CollectiveUserSettingsSetPageOrderData = {
	body: {
		/**
		 * Selected page order
		 */
		pageOrder: number
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/userSettings/pageOrder'
}

export type CollectiveUserSettingsSetPageOrderErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type CollectiveUserSettingsSetPageOrderError = CollectiveUserSettingsSetPageOrderErrors[keyof CollectiveUserSettingsSetPageOrderErrors]

export type CollectiveUserSettingsSetPageOrderResponses = {
	/**
	 * showMembers settings was set
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type CollectiveUserSettingsSetPageOrderResponse = CollectiveUserSettingsSetPageOrderResponses[keyof CollectiveUserSettingsSetPageOrderResponses]

export type CollectiveUserSettingsSetShowMembersData = {
	body: {
		/**
		 * Whether members widget on landing page is expanded or not
		 */
		showMembers: boolean
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/userSettings/showMembers'
}

export type CollectiveUserSettingsSetShowMembersErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type CollectiveUserSettingsSetShowMembersError = CollectiveUserSettingsSetShowMembersErrors[keyof CollectiveUserSettingsSetShowMembersErrors]

export type CollectiveUserSettingsSetShowMembersResponses = {
	/**
	 * showMembers setting was set
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type CollectiveUserSettingsSetShowMembersResponse = CollectiveUserSettingsSetShowMembersResponses[keyof CollectiveUserSettingsSetShowMembersResponses]

export type CollectiveUserSettingsSetShowRecentPagesData = {
	body: {
		/**
		 * Whether recent pages widget on landing page is expanded or not
		 */
		showRecentPages: boolean
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/userSettings/showRecentPages'
}

export type CollectiveUserSettingsSetShowRecentPagesErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type CollectiveUserSettingsSetShowRecentPagesError = CollectiveUserSettingsSetShowRecentPagesErrors[keyof CollectiveUserSettingsSetShowRecentPagesErrors]

export type CollectiveUserSettingsSetShowRecentPagesResponses = {
	/**
	 * showRecentPages setting was set
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type CollectiveUserSettingsSetShowRecentPagesResponse = CollectiveUserSettingsSetShowRecentPagesResponses[keyof CollectiveUserSettingsSetShowRecentPagesResponses]

export type CollectiveUserSettingsSetFavoritePagesData = {
	body: {
		/**
		 * JSON stringified array with favorite page IDs
		 */
		favoritePages: string
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/userSettings/favoritePages'
}

export type CollectiveUserSettingsSetFavoritePagesErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type CollectiveUserSettingsSetFavoritePagesError = CollectiveUserSettingsSetFavoritePagesErrors[keyof CollectiveUserSettingsSetFavoritePagesErrors]

export type CollectiveUserSettingsSetFavoritePagesResponses = {
	/**
	 * page favorites were set
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type CollectiveUserSettingsSetFavoritePagesResponse = CollectiveUserSettingsSetFavoritePagesResponses[keyof CollectiveUserSettingsSetFavoritePagesResponses]

export type SessionCloseData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
	}
	query: {
		/**
		 * Token of the session
		 */
		token: string
	}
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/sessions'
}

export type SessionCloseErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type SessionCloseError = SessionCloseErrors[keyof SessionCloseErrors]

export type SessionCloseResponses = {
	/**
	 * Session closed or not found
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type SessionCloseResponse = SessionCloseResponses[keyof SessionCloseResponses]

export type SessionCreateData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/sessions'
}

export type SessionCreateErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type SessionCreateError = SessionCreateErrors[keyof SessionCreateErrors]

export type SessionCreateResponses = {
	/**
	 * Session created, token returned
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				token: string
			}
		}
	}
}

export type SessionCreateResponse = SessionCreateResponses[keyof SessionCreateResponses]

export type SessionSyncData = {
	body: {
		/**
		 * Token of the session
		 */
		token: string
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * ID of the collective
		 */
		collectiveId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/collectives/{collectiveId}/sessions'
}

export type SessionSyncErrors = {
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Session not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type SessionSyncError = SessionSyncErrors[keyof SessionSyncErrors]

export type SessionSyncResponses = {
	/**
	 * Session updated
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type SessionSyncResponse = SessionSyncResponses[keyof SessionSyncResponses]

export type SettingsGetUserSettingData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		/**
		 * The key to get
		 */
		key: string
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/settings/user/{key}'
}

export type SettingsGetUserSettingErrors = {
	/**
	 * Invalid key
	 */
	400: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type SettingsGetUserSettingError = SettingsGetUserSettingErrors[keyof SettingsGetUserSettingErrors]

export type SettingsGetUserSettingResponses = {
	/**
	 * Valid key, value returned
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				[key: string]: string
			}
		}
	}
}

export type SettingsGetUserSettingResponse = SettingsGetUserSettingResponses[keyof SettingsGetUserSettingResponses]

export type SettingsSetUserSettingData = {
	body: {
		/**
		 * The key to set
		 */
		key: string
		/**
		 * The value
		 */
		value: string
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/settings/user'
}

export type SettingsSetUserSettingErrors = {
	/**
	 * Invalid key
	 */
	400: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Current user is not logged in
	 */
	401: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type SettingsSetUserSettingError = SettingsSetUserSettingErrors[keyof SettingsSetUserSettingErrors]

export type SettingsSetUserSettingResponses = {
	/**
	 * Valid key set to value
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				[key: string]: string
			}
		}
	}
}

export type SettingsSetUserSettingResponse = SettingsSetUserSettingResponses[keyof SettingsSetUserSettingResponses]

export type PublicCollectiveGetData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}'
}

export type PublicCollectiveGetErrors = {
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Public collective/page share not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicCollectiveGetError = PublicCollectiveGetErrors[keyof PublicCollectiveGetErrors]

export type PublicCollectiveGetResponses = {
	/**
	 * Public collective/page share returned
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				collectives: Array<Collective>
			}
		}
	}
}

export type PublicCollectiveGetResponse = PublicCollectiveGetResponses[keyof PublicCollectiveGetResponses]

export type PublicPageContentSearchData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
	}
	query: {
		/**
		 * String to search for
		 */
		searchString: string
	}
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/search'
}

export type PublicPageContentSearchErrors = {
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicPageContentSearchError = PublicPageContentSearchErrors[keyof PublicPageContentSearchErrors]

export type PublicPageContentSearchResponses = {
	/**
	 * Found pages returned
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				pages: Array<PageInfo>
			}
		}
	}
}

export type PublicPageContentSearchResponse = PublicPageContentSearchResponses[keyof PublicPageContentSearchResponses]

export type PublicPageIndexData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/pages'
}

export type PublicPageIndexErrors = {
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Public collective/page share not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicPageIndexError = PublicPageIndexErrors[keyof PublicPageIndexErrors]

export type PublicPageIndexResponses = {
	/**
	 * Pages returned
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				pages: Array<PageInfo>
			}
		}
	}
}

export type PublicPageIndexResponse = PublicPageIndexResponses[keyof PublicPageIndexResponses]

export type PublicPageTrashData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
		/**
		 * ID of the page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/pages/{id}'
}

export type PublicPageTrashErrors = {
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicPageTrashError = PublicPageTrashErrors[keyof PublicPageTrashErrors]

export type PublicPageTrashResponses = {
	/**
	 * Page trashed
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				page: PageInfo
			}
		}
	}
}

export type PublicPageTrashResponse = PublicPageTrashResponses[keyof PublicPageTrashResponses]

export type PublicPageGetData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
		/**
		 * ID of the page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/pages/{id}'
}

export type PublicPageGetErrors = {
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicPageGetError = PublicPageGetErrors[keyof PublicPageGetErrors]

export type PublicPageGetResponses = {
	/**
	 * Page returned
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				page: PageInfo
			}
		}
	}
}

export type PublicPageGetResponse = PublicPageGetResponses[keyof PublicPageGetResponses]

export type PublicPageMoveOrCopyData = {
	body?: {
		/**
		 * ID of target parent page (optional)
		 */
		parentId?: number | null
		/**
		 * Target title (optional)
		 */
		title?: string | null
		/**
		 * Index in subpage order (optional, default 0)
		 */
		index?: number | null
		/**
		 * Copy the page instead of move (optional, default false)
		 */
		copy?: boolean
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
		/**
		 * ID of the page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/pages/{id}'
}

export type PublicPageMoveOrCopyErrors = {
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or (parent) page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicPageMoveOrCopyError = PublicPageMoveOrCopyErrors[keyof PublicPageMoveOrCopyErrors]

export type PublicPageMoveOrCopyResponses = {
	/**
	 * Page moved/copied
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				page: PageInfo
			}
		}
	}
}

export type PublicPageMoveOrCopyResponse = PublicPageMoveOrCopyResponses[keyof PublicPageMoveOrCopyResponses]

export type PublicPageCreateData = {
	body: {
		/**
		 * Title of the page
		 */
		title: string
		/**
		 * ID of the template page to use
		 */
		templateId?: number | null
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
		/**
		 * ID of the parent page
		 */
		parentId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/pages/{parentId}'
}

export type PublicPageCreateErrors = {
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or parent/template page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicPageCreateError = PublicPageCreateErrors[keyof PublicPageCreateErrors]

export type PublicPageCreateResponses = {
	/**
	 * New page created
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				page: PageInfo
			}
		}
	}
}

export type PublicPageCreateResponse = PublicPageCreateResponses[keyof PublicPageCreateResponses]

export type PublicPageTouchData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
		/**
		 * ID of the page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/pages/{id}/touch'
}

export type PublicPageTouchErrors = {
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or parent/template page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicPageTouchError = PublicPageTouchErrors[keyof PublicPageTouchErrors]

export type PublicPageTouchResponses = {
	/**
	 * Page touched
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				page: PageInfo
			}
		}
	}
}

export type PublicPageTouchResponse = PublicPageTouchResponses[keyof PublicPageTouchResponses]

export type PublicPageSetFullWidthData = {
	body: {
		/**
		 * Whether to enable full width view for the page
		 */
		fullWidth: boolean
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
		/**
		 * ID of the page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/pages/{id}/fullWidth'
}

export type PublicPageSetFullWidthErrors = {
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicPageSetFullWidthError = PublicPageSetFullWidthErrors[keyof PublicPageSetFullWidthErrors]

export type PublicPageSetFullWidthResponses = {
	/**
	 * Full width view set/unset
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				page: PageInfo
			}
		}
	}
}

export type PublicPageSetFullWidthResponse = PublicPageSetFullWidthResponses[keyof PublicPageSetFullWidthResponses]

export type PublicPageSetEmojiData = {
	body?: {
		/**
		 * Emoji to set or null to unset (optional, default null)
		 */
		emoji?: string | null
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
		/**
		 * ID of the page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/pages/{id}/emoji'
}

export type PublicPageSetEmojiErrors = {
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicPageSetEmojiError = PublicPageSetEmojiErrors[keyof PublicPageSetEmojiErrors]

export type PublicPageSetEmojiResponses = {
	/**
	 * Emoji set/unset
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				page: PageInfo
			}
		}
	}
}

export type PublicPageSetEmojiResponse = PublicPageSetEmojiResponses[keyof PublicPageSetEmojiResponses]

export type PublicPageSetSubpageOrderData = {
	body?: {
		/**
		 * JSON-stringified array of subpage IDs
		 */
		subpageOrder?: string | null
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
		/**
		 * ID of the page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/pages/{id}/subpageOrder'
}

export type PublicPageSetSubpageOrderErrors = {
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicPageSetSubpageOrderError = PublicPageSetSubpageOrderErrors[keyof PublicPageSetSubpageOrderErrors]

export type PublicPageSetSubpageOrderResponses = {
	/**
	 * Subpage order set
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				page: PageInfo
			}
		}
	}
}

export type PublicPageSetSubpageOrderResponse = PublicPageSetSubpageOrderResponses[keyof PublicPageSetSubpageOrderResponses]

export type PublicPageRemoveTagData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
		/**
		 * ID of the page
		 */
		id: number
		/**
		 * ID of the tag to remove
		 */
		tagId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/pages/{id}/tags/{tagId}'
}

export type PublicPageRemoveTagErrors = {
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicPageRemoveTagError = PublicPageRemoveTagErrors[keyof PublicPageRemoveTagErrors]

export type PublicPageRemoveTagResponses = {
	/**
	 * Tag removed
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				page: PageInfo
			}
		}
	}
}

export type PublicPageRemoveTagResponse = PublicPageRemoveTagResponses[keyof PublicPageRemoveTagResponses]

export type PublicPageAddTagData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
		/**
		 * ID of the page
		 */
		id: number
		/**
		 * ID of the tag to add
		 */
		tagId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/pages/{id}/tags/{tagId}'
}

export type PublicPageAddTagErrors = {
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicPageAddTagError = PublicPageAddTagErrors[keyof PublicPageAddTagErrors]

export type PublicPageAddTagResponses = {
	/**
	 * Tag added
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				page: PageInfo
			}
		}
	}
}

export type PublicPageAddTagResponse = PublicPageAddTagResponses[keyof PublicPageAddTagResponses]

export type PublicPageGetAttachmentsData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
		/**
		 * ID of the page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/pages/{id}/attachments'
}

export type PublicPageGetAttachmentsErrors = {
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicPageGetAttachmentsError = PublicPageGetAttachmentsErrors[keyof PublicPageGetAttachmentsErrors]

export type PublicPageGetAttachmentsResponses = {
	/**
	 * Attachments returned
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				attachments: Array<PageAttachment>
			}
		}
	}
}

export type PublicPageGetAttachmentsResponse = PublicPageGetAttachmentsResponses[keyof PublicPageGetAttachmentsResponses]

export type PublicPageUploadAttachmentData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
		/**
		 * ID of the page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/pages/{id}/attachments'
}

export type PublicPageUploadAttachmentErrors = {
	/**
	 * Invalid file upload
	 */
	400: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicPageUploadAttachmentError = PublicPageUploadAttachmentErrors[keyof PublicPageUploadAttachmentErrors]

export type PublicPageUploadAttachmentResponses = {
	/**
	 * Attachment uploaded
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				attachment: PageAttachment
			}
		}
	}
}

export type PublicPageUploadAttachmentResponse = PublicPageUploadAttachmentResponses[keyof PublicPageUploadAttachmentResponses]

export type PublicPageDeleteAttachmentData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
		/**
		 * ID of the page
		 */
		id: number
		/**
		 * ID of the attachment
		 */
		attachmentId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/pages/{id}/attachments/{attachmentId}'
}

export type PublicPageDeleteAttachmentErrors = {
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or attachment not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicPageDeleteAttachmentError = PublicPageDeleteAttachmentErrors[keyof PublicPageDeleteAttachmentErrors]

export type PublicPageDeleteAttachmentResponses = {
	/**
	 * Attachment deleted
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicPageDeleteAttachmentResponse = PublicPageDeleteAttachmentResponses[keyof PublicPageDeleteAttachmentResponses]

export type PublicPageRenameAttachmentData = {
	body: {
		/**
		 * Target name
		 */
		name: string
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
		/**
		 * ID of the page
		 */
		id: number
		/**
		 * ID of the attachment
		 */
		attachmentId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/pages/{id}/attachments/{attachmentId}'
}

export type PublicPageRenameAttachmentErrors = {
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or attachment not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicPageRenameAttachmentError = PublicPageRenameAttachmentErrors[keyof PublicPageRenameAttachmentErrors]

export type PublicPageRenameAttachmentResponses = {
	/**
	 * Attachment renamed
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				attachment: PageAttachment
			}
		}
	}
}

export type PublicPageRenameAttachmentResponse = PublicPageRenameAttachmentResponses[keyof PublicPageRenameAttachmentResponses]

export type PublicPageRestoreAttachmentData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
		/**
		 * ID of the page
		 */
		id: number
		/**
		 * ID of the attachment
		 */
		attachmentId: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/pages/{id}/attachments/trash/{attachmentId}'
}

export type PublicPageRestoreAttachmentErrors = {
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or attachment not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicPageRestoreAttachmentError = PublicPageRestoreAttachmentErrors[keyof PublicPageRestoreAttachmentErrors]

export type PublicPageRestoreAttachmentResponses = {
	/**
	 * Attachment restored
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				attachment: PageAttachment
			}
		}
	}
}

export type PublicPageRestoreAttachmentResponse = PublicPageRestoreAttachmentResponses[keyof PublicPageRestoreAttachmentResponses]

export type PublicPageTrashIndexData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/pages/trash'
}

export type PublicPageTrashIndexErrors = {
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Public collective/page share not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicPageTrashIndexError = PublicPageTrashIndexErrors[keyof PublicPageTrashIndexErrors]

export type PublicPageTrashIndexResponses = {
	/**
	 * Trashed pages returned
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				pages: Array<PageInfo>
			}
		}
	}
}

export type PublicPageTrashIndexResponse = PublicPageTrashIndexResponses[keyof PublicPageTrashIndexResponses]

export type PublicPageTrashDeleteData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
		/**
		 * ID of the trashed page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/pages/trash/{id}'
}

export type PublicPageTrashDeleteErrors = {
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicPageTrashDeleteError = PublicPageTrashDeleteErrors[keyof PublicPageTrashDeleteErrors]

export type PublicPageTrashDeleteResponses = {
	/**
	 * Trashed page deleted
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicPageTrashDeleteResponse = PublicPageTrashDeleteResponses[keyof PublicPageTrashDeleteResponses]

export type PublicPageTrashRestoreData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
		/**
		 * ID of the trashed page
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/pages/trash/{id}'
}

export type PublicPageTrashRestoreErrors = {
	/**
	 * Not Permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or page not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicPageTrashRestoreError = PublicPageTrashRestoreErrors[keyof PublicPageTrashRestoreErrors]

export type PublicPageTrashRestoreResponses = {
	/**
	 * Trashed page restored
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				page: PageInfo
			}
		}
	}
}

export type PublicPageTrashRestoreResponse = PublicPageTrashRestoreResponses[keyof PublicPageTrashRestoreResponses]

export type PublicTemplateIndexData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/pages/templates'
}

export type PublicTemplateIndexErrors = {
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Public collective/page share not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicTemplateIndexError = PublicTemplateIndexErrors[keyof PublicTemplateIndexErrors]

export type PublicTemplateIndexResponses = {
	/**
	 * Template pages returned
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				templates: Array<PageInfo>
			}
		}
	}
}

export type PublicTemplateIndexResponse = PublicTemplateIndexResponses[keyof PublicTemplateIndexResponses]

export type PublicTagIndexData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/tags'
}

export type PublicTagIndexErrors = {
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Something not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicTagIndexError = PublicTagIndexErrors[keyof PublicTagIndexErrors]

export type PublicTagIndexResponses = {
	/**
	 * Tags returned
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				tags: Array<Tag>
			}
		}
	}
}

export type PublicTagIndexResponse = PublicTagIndexResponses[keyof PublicTagIndexResponses]

export type PublicTagCreateData = {
	body: {
		/**
		 * Name of the tag
		 */
		name: string
		/**
		 * Color of the tag
		 */
		color: string
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/tags'
}

export type PublicTagCreateErrors = {
	/**
	 * Tag already exists for the collective
	 */
	400: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicTagCreateError = PublicTagCreateErrors[keyof PublicTagCreateErrors]

export type PublicTagCreateResponses = {
	/**
	 * Tag created
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				tag: Tag
				info: string
			}
		}
	}
}

export type PublicTagCreateResponse = PublicTagCreateResponses[keyof PublicTagCreateResponses]

export type PublicTagDeleteData = {
	body?: never
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
		/**
		 * ID of the tag
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/tags/{id}'
}

export type PublicTagDeleteErrors = {
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or tag not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicTagDeleteError = PublicTagDeleteErrors[keyof PublicTagDeleteErrors]

export type PublicTagDeleteResponses = {
	/**
	 * Tag deleted
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicTagDeleteResponse = PublicTagDeleteResponses[keyof PublicTagDeleteResponses]

export type PublicTagUpdateData = {
	body: {
		/**
		 * Name of the tag
		 */
		name: string
		/**
		 * Color of the tag
		 */
		color: string
	}
	headers: {
		/**
		 * Required to be true for the API request to pass
		 */
		'OCS-APIRequest': boolean
	}
	path: {
		apiVersion: '1.0'
		token: string
		/**
		 * ID of the tag
		 */
		id: number
	}
	query?: never
	url: '/ocs/v2.php/apps/collectives/api/v{apiVersion}/p/collectives/{token}/tags/{id}'
}

export type PublicTagUpdateErrors = {
	/**
	 * Not permitted
	 */
	403: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
	/**
	 * Collective or tag not found
	 */
	404: {
		ocs: {
			meta: OcsMeta
			data: unknown
		}
	}
}

export type PublicTagUpdateError = PublicTagUpdateErrors[keyof PublicTagUpdateErrors]

export type PublicTagUpdateResponses = {
	/**
	 * Tag updated
	 */
	200: {
		ocs: {
			meta: OcsMeta
			data: {
				tag: Tag
			}
		}
	}
}

export type PublicTagUpdateResponse = PublicTagUpdateResponses[keyof PublicTagUpdateResponses]
